# Generated by Django 3.0.4 on 2020-03-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=128, verbose_name="Championat's years")),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Team name')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='championat.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.IntegerField(default=0)),
                ('visitors_goals', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(null=True, verbose_name='Game time')),
                ('home', models.ManyToManyField(related_name='home', to='championat.Team', verbose_name='Home')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championat.Season')),
                ('visitors', models.ManyToManyField(related_name='visitors', to='championat.Team', verbose_name='Visitors')),
            ],
        ),
    ]
