# Generated by Django 3.0.4 on 2020-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='off',
            field=models.BooleanField(default=False),
        ),
    ]
