# Generated by Django 3.0.4 on 2020-03-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0002_game_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Group name'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='group',
        ),
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.ManyToManyField(null=True, related_name='group', to='championat.Group'),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='League name')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='championat.Season')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='championat.League'),
            preserve_default=False,
        ),
    ]
