# Generated by Django 3.0.4 on 2020-03-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0004_auto_20200320_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.ManyToManyField(related_name='group', to='championat.Group'),
        ),
    ]
