# Generated by Django 3.0.4 on 2020-03-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0006_season_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(default=2020, unique=True, verbose_name="Championat's years"),
        ),
    ]
