# Generated by Django 3.0.4 on 2020-03-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0008_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(null=True, upload_to='league_logo'),
        ),
    ]
