# Generated by Django 3.0.4 on 2020-03-23 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0009_league_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='championat.Group'),
        ),
        migrations.AddField(
            model_name='game',
            name='tour',
            field=models.CharField(max_length=64, null=True, verbose_name='Group tour'),
        ),
    ]
