# Generated by Django 3.0.4 on 2020-03-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0011_auto_20200324_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='home_goals',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='visitors_goals',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
