# Generated by Django 3.0.4 on 2020-04-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0012_auto_20200324_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championat', models.CharField(max_length=256, verbose_name="Championat's name")),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='championats', to='championat.Season', verbose_name="Championat's season")),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='season',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.DateTimeField(unique=True, verbose_name='Game time slot')),
                ('championat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='championat.Championat', verbose_name="Championat's slot")),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='championat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='championat.Championat'),
        ),
    ]
