# Generated by Django 3.0.4 on 2020-04-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0013_auto_20200401_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
    ]
