# Generated by Django 3.0.4 on 2020-04-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0014_auto_20200401_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='championat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='championat.Championat'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='championat.TimeSlot', verbose_name='Game time'),
        ),
    ]
