# Generated by Django 3.0.4 on 2020-04-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0015_auto_20200401_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Default game slot')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=7, verbose_name='Day of week')),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='onetime_games',
            field=models.IntegerField(default=1, verbose_name='Number of onetime games'),
        ),
    ]
