# Generated by Django 3.0.4 on 2020-04-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0017_defaulttimeslot_championat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttimeslot',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6, verbose_name='Day of week'),
        ),
    ]
