# Generated by Django 3.0.4 on 2020-04-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0018_auto_20200401_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttimeslot',
            name='onetime_games',
            field=models.IntegerField(default=1, verbose_name='Number of onetime games'),
        ),
    ]
