# Generated by Django 3.0.4 on 2020-04-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0019_defaulttimeslot_onetime_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttimeslot',
            name='onetime_games',
            field=models.IntegerField(default=2, verbose_name='Number of onetime games'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='onetime_games',
            field=models.IntegerField(default=2, verbose_name='Number of onetime games'),
        ),
    ]
