# Generated by Django 3.0.4 on 2020-04-01 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0020_auto_20200401_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='accepted_date',
            field=models.BooleanField(default=False, verbose_name='Is game time accept'),
        ),
        migrations.AddField(
            model_name='game',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of last changes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='off',
            field=models.BooleanField(default=False, verbose_name='Is game ended'),
        ),
    ]
