# Generated by Django 3.0.4 on 2020-04-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_playerbid'),
        ('championat', '0025_championat_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended', models.BooleanField(default=False, verbose_name='Is bid sended')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='Send bid date')),
                ('accepted', models.BooleanField(default=False, verbose_name='Is bid accepted by admin')),
                ('accepted_date', models.DateTimeField(null=True, verbose_name='Send bid date')),
                ('championat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_bids', to='championat.Championat', verbose_name='Team bid for championat')),
                ('players', models.ManyToManyField(to='accounts.Player', verbose_name='Players in bid')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_bids', to='championat.Team', verbose_name="Team' bid")),
            ],
        ),
    ]
