# Generated by Django 3.0.4 on 2020-04-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0026_teambid'),
    ]

    operations = [
        migrations.AddField(
            model_name='championat',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='hampionat finished'),
        ),
    ]
