# Generated by Django 3.0.4 on 2020-04-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0027_championat_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championat',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='Championat finished'),
        ),
    ]
