# Generated by Django 3.0.4 on 2020-04-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0028_auto_20200418_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambid',
            name='declined',
            field=models.BooleanField(default=False, verbose_name='Is bid declined by admin'),
        ),
        migrations.AlterField(
            model_name='teambid',
            name='accepted_date',
            field=models.DateTimeField(null=True, verbose_name='Accept bid date'),
        ),
    ]
