# Generated by Django 3.0.4 on 2020-04-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0029_auto_20200418_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionTeamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspension', models.BooleanField(default=True, verbose_name='Suspensioned')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspension_team', to='championat.Group', verbose_name='Group of suspension')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='championat.Team', verbose_name='Suspensioned team')),
            ],
        ),
    ]
