# Generated by Django 3.0.4 on 2020-08-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0033_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preread',
            field=models.TextField(blank=True, null=True, verbose_name='Preread for card'),
        ),
    ]
