version: "3.6"

services:
  ulc_db:
    image: postgres:11
    container_name: ulc_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=ulc
    networks:
      - translate-network
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
      - ${DB_DUMP}:/docker-entrypoint-initdb.d

  ulc_site:
    image: ulc:latest
    container_name: ulc_site
    environment:
      - C_FORCE_ROOT='true'
      - PYTHONUNBUFFERED=1
    ports:
      - 7998:8000
    depends_on:
      - translater_db
    networks:
      - translate-network
    volumes:
      - ${SITE_PATH}:/translater
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - --error-logfile - ulc.wsgi

networks:
  translate-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}