# Generated by Django 3.0.4 on 2020-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='logo',
            field=models.ImageField(null=True, upload_to='players_logo'),
        ),
    ]
