# Generated by Django 3.0.4 on 2020-03-29 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_player_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, unique=True, verbose_name='unique registration key')),
                ('valid_date', models.DateTimeField(verbose_name='Experiation key time')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Created key date')),
                ('inactive', models.BooleanField(default=False, verbose_name='Was key used')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
