# Generated by Django 3.0.4 on 2020-03-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registrationkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Player number'),
        ),
    ]
