# Generated by Django 3.0.4 on 2020-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0025_championat_active'),
        ('accounts', '0006_auto_20200416_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birth date'),
        ),
        migrations.AddField(
            model_name='player',
            name='patronymic',
            field=models.CharField(max_length=256, null=True, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(to='championat.Team', verbose_name="Player's team"),
        ),
    ]
