# Generated by Django 3.0.4 on 2020-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200416_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=128, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='patronymic',
            field=models.CharField(max_length=128, null=True, verbose_name='Patronymic'),
        ),
    ]
