# Generated by Django 3.0.4 on 2020-04-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0025_championat_active'),
        ('accounts', '0008_auto_20200416_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended_date', models.DateTimeField(auto_now_add=True, verbose_name='Team change bid date')),
                ('accepted', models.BooleanField(default=False, verbose_name='Is bid accepted by captain')),
                ('declined', models.BooleanField(default=False, verbose_name='Is bid declined by captain')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_bids', to='accounts.Player')),
                ('source_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_teams', to='championat.Team')),
                ('target_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_teams', to='championat.Team')),
            ],
        ),
    ]
