# Generated by Django 3.0.4 on 2020-04-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0026_teambid'),
        ('accounts', '0009_playerbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCurrentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False, verbose_name='Is team current')),
                ('championat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='championat.Championat')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championat.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(through='accounts.PlayerCurrentTeam', to='championat.Team', verbose_name="Player's team"),
        ),
    ]
