# Generated by Django 3.0.4 on 2020-04-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_player_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inst',
            field=models.CharField(default='-', max_length=128, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='player',
            name='vk',
            field=models.CharField(default='-', max_length=128, verbose_name='VK link'),
        ),
    ]
