# Generated by Django 3.0.4 on 2020-04-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200418_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.AddField(
            model_name='playercurrentteam',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Player number'),
        ),
    ]
