# Generated by Django 3.0.4 on 2020-04-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championat', '0028_auto_20200418_0913'),
        ('accounts', '0013_auto_20200418_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercurrentteam',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_teams', to='accounts.Player'),
        ),
        migrations.AlterField(
            model_name='playercurrentteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_teams', to='championat.Team'),
        ),
    ]
