# Generated by Django 3.0.4 on 2020-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200418_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='playercurrentteam',
            name='position',
            field=models.CharField(max_length=128, null=True, verbose_name="Player' position"),
        ),
    ]
