# Generated by Django 3.0.4 on 2020-05-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_player_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercurrentteam',
            name='position',
            field=models.CharField(choices=[('ВРТ', 'GK'), ('ЗАШ', 'DEF'), ('ПЗЦ', 'MID'), ('НАП', 'FRW')], max_length=128, null=True, verbose_name="Player' position"),
        ),
    ]
